#!/usr/bin/env python3
"""Convert a PNG level map into RGBDS include data.

The engine reserves tile IDs 0..5 for the bee sprite, so background tiles are
emitted with tile IDs starting at 6. The current renderer uses one 32x32 BG map,
so source images are padded to a full 256x256-pixel map after conversion.
"""

from __future__ import annotations

import math
import subprocess
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE = ROOT / "ASSETS" / "default_level.png"
OUT_DIR = ROOT / "BUILD" / "generated"
INC_PATH = ROOT / "SRC" / "level.inc"

BG_TILE_BASE = 6
MAX_BG_TILES = 256 - BG_TILE_BASE
MAX_BG_PALETTES = 8
MAP_WIDTH_TILES = 32
MAP_HEIGHT_TILES = 32
TILE_SIZE = 8
PALETTE_BYTES = MAX_BG_PALETTES * 4 * 2


def rel(path: Path) -> str:
    path = path.resolve()
    try:
        return path.relative_to(ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def resolve_source_path(raw_path: str) -> Path:
    path = Path(raw_path)
    if path.is_absolute():
        return path.resolve()

    cwd_path = (Path.cwd() / path).resolve()
    if cwd_path.exists():
        return cwd_path

    return (ROOT / path).resolve()


def fail(message: str) -> None:
    print(f"error: {message}", file=sys.stderr)
    raise SystemExit(1)


def normalize_png(source: Path, dest: Path) -> tuple[int, int]:
    if not source.exists():
        fail(
            f"missing source PNG: {rel(source)}\n"
            "Put your level image there, or pass a PNG path to TOOLS/png_to_level.py."
        )

    image = Image.open(source).convert("RGBA")
    width, height = image.size
    if width <= 0 or height <= 0:
        fail(f"{rel(source)} is empty")
    if width > MAP_WIDTH_TILES * TILE_SIZE or height > MAP_HEIGHT_TILES * TILE_SIZE:
        fail(
            f"{rel(source)} is {width}x{height}px, but the current BG map supports at most "
            f"{MAP_WIDTH_TILES * TILE_SIZE}x{MAP_HEIGHT_TILES * TILE_SIZE}px."
        )

    padded_width = math.ceil(width / TILE_SIZE) * TILE_SIZE
    padded_height = math.ceil(height / TILE_SIZE) * TILE_SIZE
    width_tiles = padded_width // TILE_SIZE
    height_tiles = padded_height // TILE_SIZE

    if (padded_width, padded_height) != image.size:
        fill = image.getpixel((0, 0))
        padded = Image.new("RGBA", (padded_width, padded_height), fill)
        padded.paste(image, (0, 0))
        image = padded

    image.save(dest)
    return width_tiles, height_tiles


def run_rgbgfx(
    source: Path, tiles: Path, tilemap: Path, attrmap: Path, palettes: Path
) -> None:
    cmd = [
        "rgbgfx",
        "-u",
        "-b",
        str(BG_TILE_BASE),
        "-N",
        str(MAX_BG_TILES),
        "-n",
        str(MAX_BG_PALETTES),
        "-o",
        str(tiles),
        "-t",
        str(tilemap),
        "-a",
        str(attrmap),
        "-p",
        str(palettes),
        str(source),
    ]
    result = subprocess.run(cmd, cwd=ROOT, text=True, capture_output=True)
    if result.returncode == 0:
        return

    print("rgbgfx failed while converting the default level PNG.", file=sys.stderr)
    print(
        f"Limits: max {MAX_BG_PALETTES} BG palettes, max {MAX_BG_TILES} BG tiles, "
        "max 4 colors per 8x8 tile.",
        file=sys.stderr,
    )
    print("Reduce the PNG/tileset and run `zig build` again.", file=sys.stderr)
    if result.stdout:
        print(result.stdout, file=sys.stderr, end="")
    if result.stderr:
        print(result.stderr, file=sys.stderr, end="")
    raise SystemExit(result.returncode)


def pad_map(
    source_map: Path, dest_map: Path, width_tiles: int, height_tiles: int, fill: int
) -> None:
    data = source_map.read_bytes()
    expected = width_tiles * height_tiles
    if len(data) != expected:
        fail(f"{rel(source_map)} is {len(data)} bytes, expected {expected}")

    output = bytearray([fill] * (MAP_WIDTH_TILES * MAP_HEIGHT_TILES))
    for y in range(height_tiles):
        src_start = y * width_tiles
        dst_start = y * MAP_WIDTH_TILES
        output[dst_start : dst_start + width_tiles] = data[
            src_start : src_start + width_tiles
        ]
    dest_map.write_bytes(output)


def pad_palettes(path: Path) -> None:
    data = path.read_bytes()
    if len(data) > PALETTE_BYTES:
        fail(
            f"{rel(path)} contains {len(data) // 8} palettes; "
            f"the CGB BG limit is {MAX_BG_PALETTES}."
        )
    path.write_bytes(data + bytes(PALETTE_BYTES - len(data)))


def write_include(
    source_png: Path,
    tiles: Path,
    tilemap: Path,
    attrmap: Path,
    palettes: Path,
    width_tiles: int,
    height_tiles: int,
) -> None:
    tile_count = tiles.stat().st_size // 16
    INC_PATH.write_text(
        "; This file is generated by TOOLS/png_to_level.py. Do not edit by hand.\n"
        f"; Source PNG: {rel(source_png)}\n\n"
        f"DEF DEFAULT_LEVEL_WIDTH_TILES EQU {width_tiles}\n"
        f"DEF DEFAULT_LEVEL_HEIGHT_TILES EQU {height_tiles}\n"
        f"DEF DEFAULT_LEVEL_MAP_WIDTH_TILES EQU {MAP_WIDTH_TILES}\n"
        f"DEF DEFAULT_LEVEL_MAP_HEIGHT_TILES EQU {MAP_HEIGHT_TILES}\n"
        f"DEF DEFAULT_LEVEL_BG_TILE_BASE EQU {BG_TILE_BASE}\n"
        f"DEF DEFAULT_LEVEL_BG_TILE_COUNT EQU {tile_count}\n\n"
        "LevelTiles:\n"
        f'    INCBIN "{rel(tiles)}"\n'
        "LevelTilesEnd:\n\n"
        "DefaultLevelTileMap:\n"
        f'    INCBIN "{rel(tilemap)}"\n'
        "DefaultLevelTileMapEnd:\n\n"
        "DefaultLevelAttrMap:\n"
        f'    INCBIN "{rel(attrmap)}"\n'
        "DefaultLevelAttrMapEnd:\n\n"
        "DefaultLevelBgPalettes:\n"
        f'    INCBIN "{rel(palettes)}"\n'
        "DefaultLevelBgPalettesEnd:\n",
        encoding="utf-8",
    )


def main() -> None:
    source_png = (
        resolve_source_path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SOURCE
    )

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    normalized_png = OUT_DIR / "default_level.normalized.png"
    raw_tiles = OUT_DIR / "default_level.2bpp"
    raw_tilemap = OUT_DIR / "default_level.raw.tilemap"
    raw_attrmap = OUT_DIR / "default_level.raw.attrmap"
    palettes = OUT_DIR / "default_level.pal"
    padded_tilemap = OUT_DIR / "default_level.tilemap"
    padded_attrmap = OUT_DIR / "default_level.attrmap"

    width_tiles, height_tiles = normalize_png(source_png, normalized_png)
    run_rgbgfx(normalized_png, raw_tiles, raw_tilemap, raw_attrmap, palettes)

    first_tile = (
        raw_tilemap.read_bytes()[0] if raw_tilemap.stat().st_size else BG_TILE_BASE
    )
    first_attr = raw_attrmap.read_bytes()[0] if raw_attrmap.stat().st_size else 0
    pad_map(raw_tilemap, padded_tilemap, width_tiles, height_tiles, first_tile)
    pad_map(raw_attrmap, padded_attrmap, width_tiles, height_tiles, first_attr)
    pad_palettes(palettes)
    write_include(
        source_png,
        raw_tiles,
        padded_tilemap,
        padded_attrmap,
        palettes,
        width_tiles,
        height_tiles,
    )

    print(
        f"Generated {rel(INC_PATH)} from {rel(source_png)} "
        f"({width_tiles}x{height_tiles} tiles)."
    )


if __name__ == "__main__":
    main()
